-- ============================================================================
-- DOMAIN: STOREFRONT
-- Entity: cart_sessions (carts)
-- File: carts.schema.sql
-- Purpose: Schema definition for shopping cart sessions
-- ============================================================================
-- Pattern: 4-File Entity Structure
-- 1. schema.sql  ← YOU ARE HERE
-- 2. logic.sql   (Functions, Views, Triggers)
-- 3. policies.sql (Row Level Security)
-- 4. index.sql   (Indexes & Constraints)
-- ============================================================================

-- Enable UUID extension if not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================================
-- TABLE: cart_sessions
-- ============================================================================
-- Description:
--   Shopping cart data for storefront visitors.
--   Stores cart items and customer info for each session.
--   Auto-expires after 7 days (configurable).
--
-- Key Features:
--   - Anonymous cart sessions (no authentication required)
--   - Session-based cart persistence
--   - Auto-expiry after 7 days (expires_at)
--   - Customer info collection at checkout
--   - Status tracking (active, checked_out, abandoned)
--   - Cart items stored as JSONB (flexible structure)
--
-- Access Pattern:
--   - Public: Can create, read, update carts (anonymous)
--   - Owner: Can view carts for own storefront
--   - Auto-cleanup: Expired carts (expires_at < NOW())
--
-- Related Entities:
--   - business_storefronts: Parent storefront (FK: storefront_id)
--   - storefront_products: Products in cart (referenced in cart_items JSONB)
--
-- Data Source:
--   Migrated from: sql/01-features/lapak-online.sql
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.cart_sessions (
    -- Primary Key
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    
    -- Foreign Keys
    storefront_id UUID NOT NULL REFERENCES public.business_storefronts(id) ON DELETE CASCADE,
        -- Parent storefront (which lapak this cart belongs to)
        -- CASCADE: If storefront is deleted, all carts are deleted
    
    -- ========================================================================
    -- SESSION IDENTIFIER
    -- ========================================================================
    session_id TEXT NOT NULL,
        -- Unique session identifier (UUID or browser fingerprint)
        -- Generated by client (browser localStorage or cookies)
        -- Used to retrieve cart on subsequent visits
        -- Example: "550e8400-e29b-41d4-a716-446655440000"
    
    -- ========================================================================
    -- CART DATA
    -- ========================================================================
    cart_items JSONB NOT NULL,
        -- Array of cart items stored as JSON
        -- Structure: [
        --   {
        --     "product_id": "uuid",
        --     "quantity": 2,
        --     "variant": "Ukuran L, Warna Merah",
        --     "price": 50000,
        --     "name": "Kue Lapis",
        --     "image_url": "https://..."
        --   },
        --   ...
        -- ]
        -- Validated at application level
        -- No FK constraints on product_id (performance + flexibility)
    
    -- ========================================================================
    -- CUSTOMER INFO (Collected at checkout)
    -- ========================================================================
    customer_name TEXT,
        -- Customer name (collected at checkout)
        -- NULL: Cart not yet checked out
    
    customer_phone TEXT,
        -- Customer phone number (for order confirmation)
        -- NULL: Cart not yet checked out
        -- Format: 628123456789 (Indonesia)
    
    customer_address TEXT,
        -- Customer delivery address (if applicable)
        -- NULL: Not provided or not required (pickup)
    
    -- ========================================================================
    -- STATUS
    -- ========================================================================
    status TEXT DEFAULT 'active',
        -- Cart status:
        --   'active': Customer is browsing, adding items
        --   'checked_out': Customer completed checkout (order placed)
        --   'abandoned': Customer left without checking out
        -- CHECK constraint: status IN ('active', 'checked_out', 'abandoned')
    
    -- ========================================================================
    -- TIMESTAMPS
    -- ========================================================================
    created_at TIMESTAMPTZ DEFAULT NOW(),
        -- When the cart was created (first item added)
    
    updated_at TIMESTAMPTZ DEFAULT NOW(),
        -- Last modification timestamp (item added/removed/updated)
        -- Auto-updated via update_updated_at_column() trigger
    
    expires_at TIMESTAMPTZ DEFAULT (NOW() + INTERVAL '7 days')
        -- Cart expiration timestamp
        -- Default: 7 days from creation
        -- Expired carts can be cleaned up via cron job
        -- After expiry, cart is considered abandoned
);

-- ============================================================================
-- TABLE COMMENTS
-- ============================================================================

COMMENT ON TABLE public.cart_sessions IS 
'Shopping cart sessions for storefronts. Anonymous access allowed. Auto-expires after 7 days.';

COMMENT ON COLUMN public.cart_sessions.id IS 
'Primary key UUID';

COMMENT ON COLUMN public.cart_sessions.storefront_id IS 
'Parent storefront (FK to business_storefronts). CASCADE DELETE.';

COMMENT ON COLUMN public.cart_sessions.session_id IS 
'Unique session identifier (UUID or browser fingerprint). Used to retrieve cart.';

COMMENT ON COLUMN public.cart_sessions.cart_items IS 
'Array of cart items stored as JSONB. Structure: [{product_id, quantity, variant, price, name, image_url}]';

COMMENT ON COLUMN public.cart_sessions.customer_name IS 
'Customer name (collected at checkout). NULL = not yet checked out.';

COMMENT ON COLUMN public.cart_sessions.customer_phone IS 
'Customer phone number (collected at checkout). Format: 628123456789';

COMMENT ON COLUMN public.cart_sessions.customer_address IS 
'Customer delivery address (if applicable). NULL = pickup or not provided.';

COMMENT ON COLUMN public.cart_sessions.status IS 
'Cart status: active (browsing), checked_out (order placed), abandoned (left without checkout)';

COMMENT ON COLUMN public.cart_sessions.created_at IS 
'Cart creation timestamp (first item added)';

COMMENT ON COLUMN public.cart_sessions.updated_at IS 
'Last modification timestamp (auto-updated via trigger)';

COMMENT ON COLUMN public.cart_sessions.expires_at IS 
'Cart expiration timestamp (default: 7 days from creation). Expired carts can be cleaned up.';

-- ============================================================================
-- END OF SCHEMA
-- ============================================================================
-- Next Steps:
--   1. Deploy this schema: psql -f carts.schema.sql
--   2. Apply logic: carts.logic.sql
--   3. Apply RLS policies: carts.policies.sql
--   4. Add indexes: carts.index.sql
--
-- Testing:
--   - Run: storefront.debug.sql (section: cart_sessions health)
--   - Verify: Table created, columns present, constraints valid
--   - Check: storefront_id FK works correctly
--
-- Migration Notes:
--   - ADDITIVE ONLY - No DROP operations
--   - 100% BACKWARD COMPATIBLE with existing data
--   - Preserves all existing rows in cart_sessions
--   - Expired carts cleanup should be done via cron job (cleanup_expired_carts function)
--   - Consider partitioning by created_at if table grows large (>1M rows)
-- ============================================================================
